### ISSUE TITLE
Add metadata about which view is throwing error?

### ISSUE THREAD

**Issue by christianbundy** [flumedb/flumedb#31]
I've been breaking lots of stuff lately and seeing lots of this:

```
WriteError: view stream error
    at /home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/flumedb/index.js:139:35
    at /home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/pull-stream/throughs/async-map.js:18:11
    at /home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/pull-cursor/cursor.js:7:24
    at /home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/pull-cursor/skip.js:8:25
    at /home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/pull-looper/index.js:6:5
    at /home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/looper/index.js:11:9
    at /home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/pull-looper/index.js:11:5
    at next (/home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/pull-stream/throughs/async-map.js:15:19)
    at /home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/pull-looper/index.js:6:5
  WriteError: key cannot be `null` or `undefined`
    at /home/christianbundy/src/ssbc/patchbay/node_modules/ssb-server/node_modules/flumeview-level/node_modules/levelup/lib/levelup.js:266:23
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Maybe it would be useful to log which view is throwing the error?

**Comment by christianbundy** [comment]
Maybe related:

```
Error: view stream error
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/ssb-db/node_modules/flumedb/index.js:183:35
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-stream/throughs/async-map.js:18:11
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-cursor/cursor.js:7:24
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-cursor/skip.js:8:25
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-looper/index.js:6:5
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/looper/index.js:11:9
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-looper/index.js:11:5
    at next (/home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-stream/throughs/async-map.js:15:19)
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-looper/index.js:6:5
  Error: database closed while index was building
    at seq (/home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/flumeview-level/index.js:71:32)
    at flush (/home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-write/index.js:49:7)
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-write/index.js:37:33
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-write/index.js:41:13
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-stream/throughs/async-map.js:39:20
    at mapper (/home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/ssb-db/node_modules/flumedb/index.js:75:13)
    at Array.unboxerMap (/home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/ssb-db/minimal.js:85:35)
    at chainMaps (/home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/ssb-db/minimal.js:90:14)
    at asyncMap (/home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/ssb-db/node_modules/flumedb/index.js:71:9)
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-stream/throughs/async-map.js:32:13
util.js:261
  const ctx = {
              ^

RangeError: Maximum call stack size exceeded
    at inspect (util.js:261:15)
    at format (util.js:160:12)
    at Console.warn (console.js:145:21)
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/ssb-db/node_modules/flumedb/index.js:183:29
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-stream/throughs/async-map.js:18:11
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-cursor/cursor.js:7:24
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-cursor/skip.js:8:25
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-looper/index.js:6:5
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/looper/index.js:11:9
    at /home/christianbundy/src/flumedb-delete/node_modules/ssb-server/node_modules/pull-looper/index.js:11:5
```

**Comment by dominictarr** [comment]
https://github.com/flumedb/flumedb/blame/master/index.js#L139

that would be an easy change

**Comment by christianbundy** [comment]
Looks like this is resolved, thanks!
