### ISSUE TITLE
Cannot read property '@8Qee0I/DwI5DHSCi3p5fsl6FyLGArrnDz3ox9qZr5Qc=.ed25519' of undefined

### ISSUE THREAD

**Issue by evbogue** [flumedb/flumedb#9]
I've been trying to get the flumeview_reduce branch of minbase going again, and I keep encountering this error. 

This used to work, so I'm not sure what changed. 

I'm working off this branch of minbase: https://github.com/evbogue/minbase/tree/flume

```
Cannot read property '@8Qee0I/DwI5DHSCi3p5fsl6FyLGArrnDz3ox9qZr5Qc=.ed25519' of undefined
TypeError: Cannot read property '@8Qee0I/DwI5DHSCi3p5fsl6FyLGArrnDz3ox9qZr5Qc=.ed25519' of undefined
    at /home/ev/minbase_flume/modules/relationships.js:79:25
    at Object.get (/home/ev/minbase_flume/node_modules/flumeview-reduce/inject.js:102:11)
    at /home/ev/minbase_flume/modules/relationships.js:77:14
    at Function.many.once (/home/ev/minbase_flume/node_modules/flumeview-reduce/node_modules/obv/index.js:38:49)
    at /home/ev/minbase_flume/modules/relationships.js:76:18
    at /home/ev/minbase_flume/node_modules/pull-cont/source.js:18:5
    at next (/home/ev/minbase_flume/node_modules/pull-stream/throughs/filter.js:14:9)
    at next (/home/ev/minbase_flume/node_modules/pull-stream/sinks/drain.js:16:11)
    at sink (/home/ev/minbase_flume/node_modules/pull-stream/sinks/drain.js:37:9)
    at pull (/home/ev/minbase_flume/node_modules/pull-stream/pull.js:41:14)
```

**Comment by dominictarr** [comment]
this is not a flumedb error, this is a error within a specific flumeview-reduce view. 
`at /home/ev/minbase_flume/modules/relationships.js:79:25`
